/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import java.util.ArrayList;

/**
 *
 * @author eavendano
 */
public class FrmSearchResult extends javax.swing.JFrame {

    ArrayList<String> _SearchResult = new ArrayList<String>();
    ArrayList<Integer> _WordApearances = new ArrayList<Integer>();
    ArrayList<Integer> _MatchesInFileLIne = new ArrayList<Integer>();
    
    /**
     * Creates new form FrmSearchResult
     */
    public FrmSearchResult() {
        initComponents();
    }
    
    public void InsertResult(ArrayList<String> pSearchResult){
        int appearancesIndex = 0;
        for(int i = 0; i < pSearchResult.size(); i++){
            if(pSearchResult.get(i).equals("--")){
                this.txtAreaSearchResult.setText(this.txtAreaSearchResult.getText() + "\nGrand Total: "  + " match(es) found."+ "\n************************\n\n");
                appearancesIndex++;
            } else {
                this.txtAreaSearchResult.setText(this.txtAreaSearchResult.getText() + pSearchResult.get(i) + "\n");
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSearchResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaSearchResult.setEditable(false);
        txtAreaSearchResult.setColumns(20);
        txtAreaSearchResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaSearchResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSearchResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaSearchResult;
    // End of variables declaration//GEN-END:variables

    public void InsertWordAppearances(ArrayList<Integer> wordAppeareances) {
        this._WordApearances = wordAppeareances;
    }

    public void setMatchesInFileLIne(ArrayList<Integer> _MatchesInFileLIne) {
        this._MatchesInFileLIne = _MatchesInFileLIne;
    }
}
